apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: kube-system
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubesure.*
      format json
      read_from_head true
    </source>
    <match kubesure.var.log.containers.**fluentd**.log>
      @type null
    </match>
    <match kubesure.var.log.containers.**kube-system**.log>
      @type null
    </match>
    <match kubesure.var.log.containers.**monitoring**.log>
      @type null
    </match>
    #<match kubesure.**>
    # @type stdout
   #</match>
   <match kubernetes.**>
     @type elasticsearch
     host 172.31.46.92
     port 9200
     logstash_format false
     index_name kubesure.${tag}
     <buffer tag>
       @type memory 
       flush_thread_count 2
     </buffer>
   </match>
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd  
    type: cluster
    kubernetes.io/cluster-service: "true"
spec:
  template: 
    metadata:
       labels:
         app: fluentd  
         type: cluster
         kubernetes.io/cluster-service: "true"              
    spec: 
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.8
        image: fluent/fluentd:v1.3.2
        env: 
          #- name: FLUENT_ELASTICSEARCH_HOST
            #value: "172.31.46.92"
          #- name: FLUENT_ELASTICSEARCH_PORT
            #value: "9200"
          #- name: FLUENT_ELASTICSEARCH_SCHEME
            #value: "http"                   
          - name: FLUENT_UID
            value: "0" 
          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
            value: "true"
        resources: 
          limits: 
            memory: 200Mi
          requests: 
            cpu: 100m 
            memory: 200Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/    
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30                          
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-conf
      - name: varlog
        hostPath: 
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers               
     
